<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgZGy8x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgZGy8x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgZGy8x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgZGy8x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNgZGy8x\App_KernelDevDebugContainer([
    'container.build_hash' => 'NgZGy8x',
    'container.build_id' => '09b0d59e',
    'container.build_time' => 1653034618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgZGy8x');
